[[plugin.deps]]
use = "Tyarel8/goto-drives"
rev = "ea5ad4e"
hash = "8f81ee91bc039adec835886a63a86671"

[[plugin.deps]]
use = "yazi-rs/plugins:toggle-pane"
rev = "da5b695"
hash = "e24c3fe3f4e8eadb66f9cd41da6c9e58"

[[plugin.deps]]
use = "yazi-rs/plugins:git"
rev = "da5b695"
hash = "7d1b55722df54c9b7c959b2c4045932b"

[[flavor.deps]]
use = "yazi-rs/flavors:catppuccin-latte"
rev = "9276ffa"
hash = "79dc187f9ca4e1001ce0023e180227b3"

[[flavor.deps]]
use = "yazi-rs/flavors:catppuccin-frappe"
rev = "9276ffa"
hash = "22a2c137242d8e7ca18b598cc2f7e8ef"

[[flavor.deps]]
use = "yazi-rs/flavors:catppuccin-mocha"
rev = "9276ffa"
hash = "d2512b1c95c0d2bd3c15129d3fa095d6"
